config/routes.rb
Rails.application.routes.draw do

  resources :notifications, only: [:new, :create]

  root 'notifications#new'

end

app/models/notification.rb
require 'twilio-ruby'

class Notification
  attr_accessor :to_number, :from_number

  def initialize()
    self.to_number = ENV["twilio_to_number"]
    self.from_number = ENV["twilio_from_number"]
    account_sid = ENV["twilio_sid"]
    auth_token =  ENV["twilio_token"]
    @client = Twilio::REST::Client.new(account_sid, auth_token)
  end

  def text
    message = @client.account.messages.create(
    :body => random_compliment,
    :to => self.to_number,       
    :from => self.from_number)
  end

  def random_compliment
    compliments = ["A 3rd tier cable network would totally create a television show about you.", "Your handshake conveys intelligence, confidence and minor clamminess.", "Cops admire your ability to stay a perfect 3-5 miles above the speed limit.", "Your principal would call you to the office just to look cool."]
    return compliments.sample
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController

	def new
	end

  def create
  	@notification = Notification.new()
  	@notification.text

  	redirect_to root_path
  end

  private
  def notification_params
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ComplimentexterStarter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/notifications/new.html.erb
<%= form_tag notifications_path, method: "post" do %>
  <%= submit_tag "Complimentext Me" %>
<% end %>